FROM openjdk:8-jdk-alpine
EXPOSE 8086
ADD target/Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.0.war Timesheet-spring-boot-core-data-jpa-mvc-REST-1
ENTRYPOINT ["java","-jar","/Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.0.war"]